spring:
  datasource:
    initialization-mode: never
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mypassword
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true